Making dir estimator_working_dir
Making dir bucket_1/models
2018-08-30 03:36:36.004091: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
WARNING:tensorflow:CrossShardOptimizer should be used within a tpu_shard_context, but got unset number_of_shards. Assuming 1.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1305, in _run_fn
    self._extend_graph()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1340, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CrossReplicaSum' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

         [[Node: CrossReplicaSum = CrossReplicaSum[T=DT_FLOAT](gradients/AddN_102)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 157, in <module>
    argh.dispatch(parser, argv=remaining_argv[1:])
  File "/home/aaflier/.local/lib/python3.5/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/aaflier/.local/lib/python3.5/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/aaflier/.local/lib/python3.5/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "main.py", line 50, in bootstrap
    dual_net.bootstrap(working_dir)
  File "/home/aaflier/minigo/dual_net.py", line 445, in bootstrap
    sess.run(tf.global_variables_initializer())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CrossReplicaSum' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

         [[Node: CrossReplicaSum = CrossReplicaSum[T=DT_FLOAT](gradients/AddN_102)]]

Caused by op 'CrossReplicaSum', defined at:
  File "main.py", line 157, in <module>
    argh.dispatch(parser, argv=remaining_argv[1:])
  File "/home/aaflier/.local/lib/python3.5/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/aaflier/.local/lib/python3.5/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/aaflier/.local/lib/python3.5/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "main.py", line 50, in bootstrap
    dual_net.bootstrap(working_dir)
  File "/home/aaflier/minigo/dual_net.py", line 444, in bootstrap
    model_fn(features, labels, tf.estimator.ModeKeys.PREDICT)
  File "/home/aaflier/minigo/dual_net.py", line 230, in model_fn
    train_op = optimizer.minimize(combined_cost, global_step=global_step)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/optimizer.py", line 409, in minimize
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_optimizer.py", line 113, in apply_gradients
    summed_grads_and_vars.append((tpu_ops.cross_replica_sum(grad), var))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/tpu/ops/gen_tpu_ops.py", line 141, in cross_replica_sum
    "CrossReplicaSum", input=input, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3414, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'CrossReplicaSum' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

         [[Node: CrossReplicaSum = CrossReplicaSum[T=DT_FLOAT](gradients/AddN_102)]]

Waiting up to 5 seconds.
Sent all pending logs.
